name: Build iOS
on: [push,pull_request]
jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1 
      - name: Configure & Build üîß 
        run: |
          mkdir build
          cd build
          cmake -GXcode -DSOKOL_BACKEND=SOKOL_METAL -DCMAKE_SYSTEM_NAME=iOS ../
          cmake --build . --config Release -- CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=YES
          cmake .. && cmake --build .
      - name: Build DMG
        run: |
          cd build
          brew install graphicsmagick imagemagick
          npm install --global create-dmg
          create-dmg --dmg-title=SkyEmu 'bin/SkyEmu.app' || true
          mv "SkyEmu .dmg" "SkyEmu.dmg"
      - name: GH Release üöÄ
        # You may pin to the exact commit or the version.
        uses: actions/upload-artifact@v2
        with:
           name: MacOSRelease
           path: build/SkyEmu.dmg
        #uses: softprops/action-gh-release@v0.1.5
        #with:
        #  # Note-worthy description of changes in release
        #  # body: # optional
        #  # Path to load note-worthy description of changes in release from
        #  # body_path: # optional
        #  # Gives the release a custom name. Defaults to tag name
        #  name: LinuxRelease
        #  # Identify the release as a prerelease. Defaults to false
        #  prerelease: True
        #  # Newline-delimited list of path globs for asset files to upload
        #  files: build/bin/*
 
